### ISSUE TITLE
customerName is not included in CFCustomerDetails  class

### ISSUE THREAD

**Issue by chaitanya360** [cashfree/cashfree-pg-sdk-nodejs#1]
## in CFCustomerDetails class there should be a `customerName` attribute.
it is given in cashfree documentation but not included in this sdk.

**Comment by bhaskar-cashfree** [comment]
Customer name has been pushed in the latest release.

**Comment by chaitanya360** [comment]
when will it reflect here ?

**Comment by bhaskar-cashfree** [comment]
WIll be reflected in 1.0.8 version
