### ISSUE TITLE
Issues after installing cashfree-pg-sdk-nodejs package

### ISSUE THREAD

**Issue by gdpr1504** [cashfree/cashfree-pg-sdk-nodejs#5]
Error after installing the package and building the application:

![image](https://user-images.githubusercontent.com/64791710/218661069-24d936d3-52d7-426e-80f1-c80adc480827.png)

Request Package has been deprecated.

I Installed the Request Package. It lead to another error related to crypto.

![image](https://user-images.githubusercontent.com/64791710/218662181-d00afad6-5e81-454b-8543-86f1fcf5bcc7.png)

Crypto package is also deprecated.

Any solution for this? Can we do without using the request package? 

I am trying to implement the payment for individual methods using this package. Could you please provide a way to solve this issue?

**Comment by gdpr1504** [comment]
@suhas-cashfree @bhaskar-cashfree @chaitanya360 any solution?

**Comment by suhas-cashfree** [comment]
@gdpr1504 let me check this and get back to you

**Comment by gdpr1504** [comment]
okay @suhas-cashfree

**Comment by rakesh9541** [comment]
is this error still there??

**Comment by suhas-cashfree** [comment]
Is it happening for you @rakesh9541 ?

**Comment by rahulsingh81** [comment]
i order create time not recieve payment_session_id is undefiend

 orderId: 'order_3674552TNkmLwm1nunRlvyp06SKSwGkQ9',
    entity: 'order',
    orderCurrency: 'INR',
    orderAmount: 45,
    orderStatus: 'ACTIVE',
    orderToken: 'pRJcjnpvF2zfB1GyUxzd',
    paymentSessionId: undefined,
    

this code 
  const userId = request.user?.["_id"];
        const { mobile, email, amount, name } = request.body;
        const customerDetails = new CFCustomerDetails();
        customerDetails.customerId = userId;
        customerDetails.customerPhone = mobile;
        customerDetails.customerEmail = email;
        customerDetails.customerName = name;
        const orderTags = {};
        orderTags["order_tag_01"] = "TESTING IT";
        const cFOrderRequest = new CFOrderRequest();
        cFOrderRequest.orderAmount = amount;
        cFOrderRequest.orderCurrency = "INR";
        cFOrderRequest.customerDetails = customerDetails;
        cFOrderRequest.orderTags = orderTags;

        const apiInstance = new CFPaymentGateway();
        const result = await apiInstance.orderCreate(cfConfig, cFOrderRequest);

        if (result != null) {
          console.log(result?.cfOrder?.paymentSessionId);
          console.log(result?.cfOrder?.orderId);
          console.log(result?.cfHeaders);
          console.log(result);
          reply.send(result);
        }
