### ISSUE TITLE
Why does it says request failed everytime

### ISSUE THREAD

**Issue by SamarthKadam** [cashfree/cashfree-pg-sdk-nodejs#74]
why does it gives me this error all the time {
    "code": "request_failed",
    "message": "authentication Failed",
    "type": "authentication_error"
}

**Comment by suhas-cashfree** [comment]
Hi @SamarthKadam 
In which environment are you facing this issue ?

**Comment by SamarthKadam** [comment]
TEST environement

**Comment by suhas-cashfree** [comment]
Hi @SamarthKadam 
Need your merchant id to check this auth error. Please write to care@cashfree.com from your registered email id

**Comment by SamarthKadam** [comment]
@suhas-cashfree merchant id you mean the client id

**Comment by suhas-cashfree** [comment]
Yes

**Comment by SamarthKadam** [comment]
@suhas-cashfree Sent you please have a look

**Comment by Rag50** [comment]
@suhas-cashfree  i am also facing the same issue

**Comment by suhas-cashfree** [comment]
@Rag50 please write to care@cashfree.com with your client-id from your registered email address. There might be some configuration missing

**Comment by suhas-cashfree** [comment]
Closing this ticket for now. Please open a new one, if the issue still exisits
