### ISSUE TITLE
Bump axios to 1.7.4 to patch vulnerabilites

### ISSUE THREAD

**Issue by web-ainyx** [cashfree/cashfree-pg-sdk-nodejs#75]
npm audit
# npm audit report

axios  1.0.0 - 1.7.3
Severity: high
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
Server-Side Request Forgery in axios - https://github.com/advisories/GHSA-8hc4-vh64-cxmj
No fix available
node_modules/cashfree-pg/node_modules/axios
  cashfree-pg  *
  Depends on vulnerable versions of axios
  node_modules/cashfree-pg

2 vulnerabilities (1 moderate, 1 high)

Some issues need review, and may require choosing
a different dependency.

**Comment by web-ainyx** [comment]
FYA ^^ @suhas-cashfree @pranav-sdet-cashfree @bhaskar-cashfree

**Comment by suhas-cashfree** [comment]
acknowledged

**Comment by suhas-cashfree** [comment]
Moved to 1.7.7

**Comment by nikunjpsoni** [comment]
Again seeing issue in 1.8.1,

**# npm audit report**

axios  1.0.0 - 1.8.1
Severity: high
axios Requests Vulnerable To Possible SSRF and Credential Leakage via Absolute URL - https://github.com/advisories/GHSA-jr5f-v2jv-69x6
No fix available
node_modules/cashfree-pg/node_modules/axios
  cashfree-pg  *
  Depends on vulnerable versions of axios
  node_modules/cashfree-pg

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

@suhas-cashfree
