### ISSUE TITLE
Can't use SDK in multi-tenant environments

### ISSUE THREAD

**Issue by mdwt** [cashfree/cashfree-pg-sdk-nodejs#76]
We want to integrate Cashfree into our multi-tenant platform, but it seems the current implementation of the SDK doesn't allow that because all the configuration parameters are all static variables of the Cashfree class, so you can only ever have one Cashfree merchant per runtime.

```
export class Cashfree {
...
    static XClientId?: string;
    static XClientSecret?: string;
    static XPartnerKey?: string;
    static XClientSignature?: string;
    static XPartnerMerchantId?: string;
...
```

Are there any plans to change this to member variables so that one can use different instances for different merchants?

**Comment by suhas-cashfree** [comment]
Hi @mdwt 

Initially, the SDK was designed to keep it simple. But yes, this use case of multiple creds has to be supported. Will get back to you once we discuss internally.

**Comment by suhas-cashfree** [comment]
Hi @mdwt 
Use version 4.3.0
In this we have added a new method like
`Cashfree.PGCreateOrderWithConfiguration()`
This takes in a CashfreeConfiguration class as the first parameter and you can pass different merchants on each call.

**Comment by mdwt** [comment]
great thank you!

**Comment by suhas-cashfree** [comment]
Closing this for now. Please raise a new ticket if the issue still persists
