### ISSUE TITLE
paymentSessionId is undefiend

### ISSUE THREAD

**Issue by rahulsingh81** [cashfree/cashfree-pg-sdk-nodejs#8]
payment session id is undefiend 

paymentSessionId: undefined,

this code :  const userId = request.user?.["_id"];
        const { mobile, email, amount, name } = request.body;
        const customerDetails = new CFCustomerDetails();
        customerDetails.customerId = userId;
        customerDetails.customerPhone = mobile;
        customerDetails.customerEmail = email;
        customerDetails.customerName = name;
        const orderTags = {};
        orderTags["order_tag_01"] = "TESTING IT";
        const cFOrderRequest = new CFOrderRequest();
        cFOrderRequest.orderAmount = amount;
        cFOrderRequest.orderCurrency = "INR";
        cFOrderRequest.customerDetails = customerDetails;
        cFOrderRequest.orderTags = orderTags;

        const apiInstance = new CFPaymentGateway();
        const result = await apiInstance.orderCreate(cfConfig, cFOrderRequest);

        if (result != null) {
          console.log(result?.cfOrder?.paymentSessionId);
          console.log(result?.cfOrder?.orderId);
          console.log(result?.cfHeaders);
          console.log(result);
          reply.send(result);
        }

**Comment by suhas-cashfree** [comment]
What is the sdk version you are using and what is the x-api-version ?

**Comment by rahulsingh81** [comment]
"cashfree-pg-sdk-nodejs": "^2.0.2",  version use

**Comment by rahulsingh81** [comment]
Thanks @suhas-cashfree  as a change the api version perfect work
